### ISSUE TITLE
Code is not reproducible. (data.motif_batch in ginet.py)

### ISSUE THREAD

**Issue by johnnam513** [yuyangw/iMolCLR#1]
Hi. Thanks for your great work!
I tried to reproduce your experiment, but failed to do so.
The error I faced was, AttributeError: 'Batch' object has no attribute 'motif_batch'.
And I also found that there is actually no attribute 'motif_batch' in 'Batch'.
If it is possible, can you explain how to reproduce your code?
Thanks a lot!

**Comment by yuyangw** [comment]
Hi Jaehyun, 

Sorry for the delay, I've been pretty packed recently. The code has been updated to fix the bug. 

Best, 
Yuyang
