### ISSUE TITLE
'timeout!' Error

### ISSUE THREAD

**Issue by Dandelionym** [yuyangw/iMolCLR#2]
...
timeout!
timeout!
timeout!
timeout!
timeout!
timeout!
timeout!
timeout!
timeout!
Traceback (most recent call last):
  File "C:/Caffeine/iMolCLR-master/imolclr.py", line 223, in <module>
    main()
  File "C:/Caffeine/iMolCLR-master/imolclr.py", line 219, in main
    molclr.train()
  File "C:/Caffeine/iMolCLR-master/imolclr.py", line 123, in train
    loss_sub = self.nt_xent_criterion(z1_sub, z2_sub)
  File "C:\Users\it\anaconda3\envs\mo\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Caffeine\iMolCLR-master\utils\nt_xent.py", line 59, in forward
    negatives = similarity_matrix[mask_samples_from_same_repr].view(2 * batch_size, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

Above all is stdout while I'm runing this repo in the same env of MoICLR. Here my config file is the same as your source code excepting dataset. I use the same dataset with your prior work MoICLR, which is collected from PubChem, over 10m SMILES strings. (  data_path: data/pubchem-10m-clean.txt  ), which is not the same as this work's dataset.

I wonder if it is wrong that my config dataset is not the same as yours that you provided in this repo ( i.e. data_path: data/pubchem-10k.txt ). 

Thanks a lot! Your work is awesome!👍🏻  Looking forward your reply.

**Comment by Dandelionym** [comment]
Okay, above error is solved. However, the training process is highly rely on the network environment. Waiting for the training result now... 

[Good work!] 👍🏻  :-)

**Comment by Dandelionym** [comment]
@yuyangw   Sorry for mentioning you again and again. I suggest that the whole data including the fragments download form Internet could be pre-loaded yourself and uploaded to **Google Drive** if possible. Owing to the poor network in some of the countries, **it is not accessible for them to complete the whole training process without any crash**. If it is publicly open, that would be a great contribution to the community.

**Comment by yuyangw** [comment]
Thanks for your interest in our work and your suggestions. We'll consider releasing the pre-processed data. 

Best, 
Yuyang
