### ISSUE TITLE
How to define the positive pair of the fragment?

### ISSUE THREAD

**Issue by microbenh** [yuyangw/iMolCLR#3]
![image](https://user-images.githubusercontent.com/37615923/201291061-d712a6c6-8e0f-4309-a4a3-0917c64d2aba.png)
As shown in eq6 in paper, the i, j index is the positive pair of the molecules, but contrastive loss of fragments still use the i,j index, and the number of fragments(2M) is different from molecules(2N).  So which is i,j-th fragments?

**Comment by yuyangw** [comment]
Thanks for pointing this out. The total loss should be 
![image](https://user-images.githubusercontent.com/33227967/206950989-6bd961e3-4403-4c7e-a372-2a2cfef2cf42.png)
where m and n are fragments in molecules Mi and Mj, respectively.
