### ISSUE TITLE
scaled error 

### ISSUE THREAD

**Issue by liuyunwu** [yuyangw/iMolCLR#4]
Hello,

The representation in Figure 2b in the paper was drawn using which function of what tool. How do I scale each value without scaled error?

I look forward to your prompt reply. Thanks again!

Best,

**Comment by yuyangw** [comment]
Hi, 

I didn't quite get your question. There is no representation in Figure 2b of the paper. Could you please elaborate your question? Thanks 

Best, 
Yuyang
