### ISSUE TITLE
if atom and edge features are one-hot encoding, how to mask?

### ISSUE THREAD

**Issue by wuyuhui-zju** [yuyangw/iMolCLR#5]
Hello, if atom and edge features are one-hot encoding sometimes (you know, some GNNs take one-hot as input), how to mask? Have you ever tried it? Thank you.

**Comment by yuyangw** [comment]
Masking indicates replacing the feature vector with a unique vector that is different from the feature vectors so that the model gets the hints of the existence of the masked atoms but doesn't directly get the information of masked atoms.
