### ISSUE TITLE
How to Get Chirality tag and BondDir for canonical smiles

### ISSUE THREAD

**Issue by shrimonmuke0202** [yuyangw/iMolCLR#6]
Hi Team,

I have a canonical smile "CCC[NH2+]C(CCc1ccccn1)c1ccc(Cl)s1" and obtain `rdkit.Chem.rdchem.ChiralType.CHI_UNSPECIFIED` as chiral tag and `rdkit.Chem.rdchem.BondDir.NONE` for all atoms and bonds. Why does this happen? is there any alternative way to include those two properties in the molecular graph?

Again for all smiles strings that are used for pertaining of the iMolCLR produces `rdkit.Chem.rdchem.ChiralType.CHI_UNSPECIFIED` for chiraltag and `rdkit.Chem.rdchem.BondDir.NONE` for BondDIR.

**Comment by yuyangw** [comment]
The chiral tag is determined by the input molecule. For molecules that do not have chirality, the chiral tag will be `CHI_UNSPECIFIED`. An example of chiral molecules is `C[C@H]1CCC[C@@H](C)[C@@H]1Cl` which contains `CHI_TETRAHEDRAL_CW` and `CHI_TETRAHEDRAL_CCW`. 

To get `BondDir`, you will need to calculate the conformation of the molecules. For example:
```
from rdkit import Chem
from rdkit.Chem import AllChem
m = Chem.MolFromSmiles('C[C@H]1CCC[C@@H](C)[C@@H]1Cl')
AllChem.EmbedMolecule(m, randomSeed=0xf00d)
Chem.WedgeMolBonds(m, m.GetConformers()[0])
for bond in m.GetBonds():
      print(bond.GetBondDir())
```
This will contain `BEGINWEDGE` and `BEGINDASH` for `BondDir`. 

Hope this helps. 

Best,
Yuyang
